image: docker:latest

services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t app-builder -f Dockerfile.build .
    - docker create --name builder-container app-builder
    - docker cp builder-container:/artifacts/app.jar ./artifacts/app.jar
    - docker rm builder-container
  artifacts:
    paths:
      - artifacts/app.jar

deploy:
  stage: deploy
  script:
    - docker build -t run-app -f Dockerfile.run .
    - docker run run-app
