image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t app-builder -f Dockerfile.build .
    - docker create --name builder-container app-builder
    - docker cp builder-container:/artifacts/app.jar ./artifacts/app.jar
    - docker rm builder-container
  artifacts:
    paths:
      - artifacts/app.jar

deploy:
  stage: deploy
  services:
    - docker:dind
  script:
    - docker build -t run-app -f Dockerfile.run .
    - docker run run-app
