image: docker

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building the application..."
    - docker info
    - docker build -t app-builder -f Dockerfile.build .
    - docker create --name builder-container app-builder
    - docker cp builder-container:/artifacts/app.jar ./artifacts/app.jar
    - docker rm builder-container
  artifacts:
    paths:
      - artifacts/app.jar

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - docker info
    - docker build -t run-app -f Dockerfile.run .
    - docker run run-app
