stages:
  - build
  - deploy

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y ca-certificates dash
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    - chmod a+r /etc/apt/keyrings/docker.asc
    - echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sh -c 'cat > /etc/apt/sources.list.d/docker.list <<EOF
      deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable
      EOF'
    - apt-get update
    - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - docker build -t app-builder -f Dockerfile.build .
    - docker create --name builder-container app-build
    - docker cp build-container:/artifacts/app.jar ./artifacts/app.jar
    - docker rm build-container
  artifacts:
    paths:
      - artifacts/app.jar

deploy:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y ca-certificates curl dash
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    - chmod a+r /etc/apt/keyrings/docker.asc
    - echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sh -c 'cat > /etc/apt/sources.list.d/docker.list <<EOF
      deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable
      EOF'
    - apt-get update
    - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - docker build -t run-app -f Dockerfile.run .
    - docker run run-app
