image: docker:stable

services:
  - docker:dind

stages:
  - build
  - deploy

default:
  before_script:
    - docker info

build:
  stage: build
  script:
    - echo "Building the application..."
    - docker info
    - mkdir -p artifacts
    - docker build -t app-builder -f Dockerfile.build .
    - |
      if [ $(docker ps -aq -f name=builder-container) ]; then
        docker stop builder-container || true
        docker rm builder-container || true
      fi
    - docker create --name builder-container app-builder
    - docker cp builder-container:/artifacts/app.jar ./artifacts/app.jar
    - docker rm builder-container
  artifacts:
    paths:
      - artifacts/app.jar

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - docker info
    - docker build -t run-app -f Dockerfile.run .
    - docker run run-app
